/**
 * config.js — Central configuration.
 */

// Free account at https://www.jawg.io/ (75,000 tiles/month)
export const JAWG_API_KEY = 'AmqbyZ47xe9mLnAJNG7rNqIGZDFffalylyhlk7zlkaJ6hy0wPL43X6IgnkZjUT6t';

// Path to tile files — generated by TileBuilder.
export const TILES_BASE = './data/tiles/';

// Tile size in degrees — must match TileBuilder's TILE_DEG constant
export const TILE_DEG = 0.5;

// Minimum zoom level to display signals
export const MIN_ZOOM_FETCH = 11;

// Initial map view (France)
export const MAP_INITIAL_VIEW = { center: [46.8, 2.3], zoom: 6 };

// Default basemap: 'jawg-transport' | 'jawg-sunny' | 'jawg-dark' | 'osm' | 'satellite'
export const DEFAULT_BASEMAP = 'jawg-transport';
