/**
 * osm-diff.js — Pure tag comparison between app-generated tags and OSM reality.
 *
 * Scope:
 *   Compared keys are those matching the predicate passed as third argument.
 *   Default scope covers the SNCF signal tagging schema:
 *     - 'railway=signal' (top-level)
 *     - 'railway:signal:*' (category, form, plate, shape, states, ref, ...)
 *   OSM-only metadata (source, operator, note, survey:date, ...) is ignored
 *   by design so it never shows up as a false divergence.
 *
 * Public API:
 *   computeTagDiff(generated, osmTags, inScope?) — returns { divergent, hasDiff }
 */


// ===== Default comparison scope =====

/**
 * Default predicate: a key participates in the diff when it belongs to the
 * SNCF signal tagging schema. Everything outside this scope is ignored so OSM
 * metadata never surfaces as a false divergence.
 */
const DEFAULT_SCOPE = (k) =>
    k === 'railway' || k.startsWith('railway:signal:');


// ===== Public API =====

/**
 * Compute the divergence between app-generated tags and actual OSM tags.
 *
 * A key is divergent when:
 *   - it is generated by the app but missing from OSM (→ should be added),
 *   - it is generated by the app with a value different from OSM (→ value mismatch),
 *   - it is present in OSM but no longer generated by the app (→ stale, should be removed).
 *
 * @param {Map<string, string>}  generated   Tags produced by signal-mapping.
 * @param {object | null}        osmTags     Tags returned by Overpass, or null.
 * @param {(k: string) => boolean} [inScope] Which keys are compared (default: SNCF schema).
 * @returns {Map<string, { expected: string|null, actual: string|null }> | null}
 *   'expected' is the value generated by the app (null → should be removed).
 *   'actual'   is the value currently in OSM (null → should be added).
 *   Insertion order of 'divergent' reflects 'generated' first, then OSM-only keys.
 */
export function computeTagDiff(appTags, osmTags, inScope = DEFAULT_SCOPE) {
    if (!osmTags) return null;
    const generated = appTags ?? new Map();
    const divergent = new Map();

    // Pass 1 — generated keys missing or mismatched in OSM.
    // Iteration order matches 'generated', so downstream rendering stays stable.
    for (const [k, expected] of generated) {
        if (!inScope(k)) continue;
        const actual = osmTags[k] ?? null;
        if (actual !== expected) divergent.set(k, { expected, actual });
    }

    // Pass 2 — stale OSM keys no longer generated by the app.
    for (const k of Object.keys(osmTags)) {
        if (!inScope(k) || generated.has(k)) continue;
        divergent.set(k, { expected: null, actual: osmTags[k] });
    }

    return divergent.size === 0 ? null : divergent;
}
