// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Noël Danjou

/**
 * osm-export.js - Build OSM export payloads from location groups.
 *
 * Single source of node generation shared by both export formats, so the two
 * stay strictly consistent (same node splitting, same co-location offset, same
 * tags, and the SAME total node count). The DOM side (menu, popover, download)
 * lives in validate-main.js / export-panel.js.
 *
 * Node generation:
 *   For each location group, groupFeats() splits the feats into one or more OSM
 *   nodes (separate nodes come from opposite directions or category conflicts;
 *   they are intentionally kept separate). Co-located nodes are offset by
 *   NODE_OFFSET_DEG on the latitude axis so editors can select them apart.
 *
 * Two formats, one node source:
 *   buildFeatureCollection()     - standard GeoJSON FeatureCollection (all nodes
 *                                  flattened into one features array).
 *   buildMapRouletteChallenges() - line-by-line GeoJSON (NDJSON), split into one
 *                                  file per line-code bucket. Each task is a
 *                                  standalone FeatureCollection carrying a
 *                                  cooperativeWork .osc so JOSM can pre-create
 *                                  the node(s); all nodes of a location stay in
 *                                  the same task. Every location lands in exactly
 *                                  one bucket, so the union of all files
 *                                  reproduces the GeoJSON node set node-for-node.
 *
 * Bucketing:
 *   Locations are grouped by the leading digits of their SNCF line code
 *   (code_ligne, exposed as p.lineCode). The code is reduced to digits and
 *   left-padded to LINE_CODE_WIDTH, then sliced to groupDigits. groupDigits=1
 *   yields ~10 regional files; 3 yields ~80-100 axis files. Locations with no
 *   usable line code fall into a single UNKNOWN_BUCKET so none are dropped.
 *
 * MapRoulette cooperative format reference:
 *   https://github.com/osmlab/maproulette3/wiki/Cooperative-Challenges
 *   meta.version = 2, meta.type = 2 (change file), file.format = osc, base64.
 *
 * Pure module: no DOM, no app config beyond imported constants. Side-effect free.
 *
 * Public API:
 *   buildFeatureCollection(locationGroups, opts)    -> object   (GeoJSON)
 *   buildMapRouletteChallenges(locationGroups, opts)
 *       -> Array<{ label, content, taskCount, nodeCount }>  (sorted by label)
 */

import { APP_ID, NODE_OFFSET_DEG } from '../config.js';
import { buildNodeTags } from '../osm-tags.js';
import { groupFeats } from '../signal-grouping.js';

// ===== Constants =====

// Name embedded in the standard GeoJSON FeatureCollection (output string, not a comment).
const COLLECTION_NAME = 'SNCF Signalisation Permanente \u2014 OSM export';

// generator attribute written on the osmChange document.
const OSC_GENERATOR = APP_ID;

// MapRoulette cooperative metadata - only this exact combination is supported.
const MR_META = { version: 2, type: 2 };

// SNCF RFN line codes are 6 digits; shorter codes have leading zeros stripped.
const LINE_CODE_WIDTH = 6;

// Default number of leading line-code digits used to bucket challenge files.
const DEFAULT_GROUP_DIGITS = 1;

// Bucket for locations whose line code is missing or non-numeric.
const UNKNOWN_BUCKET = 'misc';

// ===== Public API =====

/**
 * Build a standard GeoJSON FeatureCollection of all exported OSM nodes.
 *
 * @param {Map<string, object>} locationGroups
 * @param {{ appUrl?: string }} [opts]  appUrl is used in the description field.
 * @returns {object}  GeoJSON FeatureCollection.
 */
export function buildFeatureCollection(locationGroups, { appUrl } = {}) {
    const features = [];
    for (const nodes of _iterLocationNodes(locationGroups.values())) {
        for (const node of nodes) features.push(_toFeature(node));
    }

    const fc = { type: 'FeatureCollection', name: COLLECTION_NAME, features };
    if (appUrl) fc.description = `Generated by ${appUrl}/validate.html`;
    return fc;
}

/**
 * Build MapRoulette cooperative challenges, one file per line-code bucket.
 *
 * One task per location group; all the location's nodes are bundled in the same
 * task (FeatureCollection + a single .osc creating every node). MapRoulette
 * auto-detects the line-by-line format, so no special extension is required.
 *
 * @param {Map<string, object>} locationGroups
 * @param {{ groupDigits?: number }} [opts]  Leading line-code digits per bucket.
 * @returns {Array<{ label: string, content: string, taskCount: number, nodeCount: number }>}
 */
export function buildMapRouletteChallenges(locationGroups, { groupDigits = DEFAULT_GROUP_DIGITS } = {}) {
    const digits = _clampDigits(groupDigits);
    const buckets = _bucketByLineCode(locationGroups, digits);

    const files = [];
    for (const [bucket, locs] of buckets) {
        const lines = [];
        let nodeCount = 0;
        for (const nodes of _iterLocationNodes(locs)) {
            nodeCount += nodes.length;
            lines.push(_buildTask(nodes));
        }
        files.push({
            label: _bucketLabel(bucket),
            content: lines.join('\n'),
            taskCount: lines.length,
            nodeCount,
        });
    }

    // Stable order so the file list and downloads are predictable.
    files.sort((a, b) => a.label.localeCompare(b.label));
    return files;
}

// ===== Node generation (shared) =====

/**
 * Yield, for each location, its array of OSM nodes.
 * Each node is { lat, lng, tags } with the co-location offset already applied.
 * Accepts any iterable of location groups so both the full export and a single
 * bucket reuse the exact same generation.
 *
 * @param {Iterable<object>} locs
 * @returns {Generator<Array<{ lat: number, lng: number, tags: Map<string,string> }>>}
 */
function* _iterLocationNodes(locs) {
    for (const loc of locs) {
        const { nodeGroups, isMech } = groupFeats(loc.feats);
        yield nodeGroups.map((ng, i) => ({
            // Offset each co-located node on the latitude axis (same constant as
            // signal-popup.js) so editors can distinguish them individually.
            lat: loc.lat + i * NODE_OFFSET_DEG,
            lng: loc.lng,
            tags: buildNodeTags(ng.feats, { isMech }),
        }));
    }
}

/** Convert one node into a GeoJSON Point Feature with OSM key=value properties. */
function _toFeature(node) {
    return {
        type: 'Feature',
        geometry: { type: 'Point', coordinates: [node.lng, node.lat] },
        properties: Object.fromEntries(node.tags),
    };
}

// ===== Line-code bucketing =====

/** Keep groupDigits within [1, LINE_CODE_WIDTH]; fall back to the default. */
function _clampDigits(n) {
    const d = Number.isInteger(n) ? n : DEFAULT_GROUP_DIGITS;
    return Math.min(Math.max(d, 1), LINE_CODE_WIDTH);
}

/**
 * Split the location groups into buckets keyed by their line-code prefix.
 * Every location lands in exactly one bucket (UNKNOWN_BUCKET when no code),
 * which guarantees the node count is preserved across all files.
 */
function _bucketByLineCode(locationGroups, digits) {
    const buckets = new Map();
    for (const loc of locationGroups.values()) {
        const key = _bucketKey(loc, digits);
        if (!buckets.has(key)) buckets.set(key, []);
        buckets.get(key).push(loc);
    }
    return buckets;
}

/** Leading-digit prefix of a location's line code, or UNKNOWN_BUCKET. */
function _bucketKey(loc, digits) {
    const lineCode = loc.feats[0]?.p.lineCode ?? '';
    const onlyDigits = lineCode.replace(/\D/g, '');
    if (!onlyDigits) return UNKNOWN_BUCKET;
    return onlyDigits.padStart(LINE_CODE_WIDTH, '0').slice(0, digits);
}

/** Human-readable bucket label, e.g. "7" -> "7xxxxx", "752" -> "752xxx". */
function _bucketLabel(bucket) {
    if (bucket === UNKNOWN_BUCKET) return UNKNOWN_BUCKET;
    return bucket + 'x'.repeat(LINE_CODE_WIDTH - bucket.length);
}

// ===== MapRoulette task building =====

/**
 * Build one line-by-line GeoJSON task: a standalone FeatureCollection plus a
 * cooperativeWork section carrying the base64-encoded .osc for its node(s).
 *
 * @param {Array<{ lat, lng, tags }>} nodes  All nodes at one location.
 * @returns {string}  A single JSON line (no trailing newline).
 */
function _buildTask(nodes) {
    const task = {
        type: 'FeatureCollection',
        features: nodes.map(_toFeature),
        cooperativeWork: {
            meta: MR_META,
            file: {
                type: 'xml',
                format: 'osc',
                encoding: 'base64',
                content: _utf8ToBase64(_buildOsc(nodes)),
            },
        },
    };
    return JSON.stringify(task);
}

/**
 * Build an OSM Change document that creates every node of a location.
 * Negative ids (-1, -2, ...) mark the nodes as new elements for JOSM.
 *
 * @param {Array<{ lat, lng, tags }>} nodes
 * @returns {string}  .osc XML.
 */
function _buildOsc(nodes) {
    const body = nodes.map((node, i) => _buildOscNode(node, -(i + 1))).join('\n');
    return `<?xml version="1.0" encoding="UTF-8"?>
<osmChange version="0.6" generator="${OSC_GENERATOR}">
  <create>
${body}
  </create>
</osmChange>`;
}

/** Build a single <node> element with its tags. */
function _buildOscNode(node, id) {
    const tags = [...node.tags]
        .map(([k, v]) => `      <tag k="${_xmlEscape(k)}" v="${_xmlEscape(v)}"/>`)
        .join('\n');
    return `    <node id="${id}" lat="${node.lat}" lon="${node.lng}" version="0" changeset="0">
${tags}
    </node>`;
}

// ===== Encoding helpers =====

/** Escape the five XML-significant characters in an attribute value. */
function _xmlEscape(value) {
    return String(value)
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&apos;');
}

/**
 * Base64-encode a UTF-8 string. btoa() is Latin1-only, so the string is first
 * encoded to bytes; per-task .osc payloads are small enough for fromCharCode.
 *
 * @param {string} str
 * @returns {string}  Base64.
 */
function _utf8ToBase64(str) {
    const bytes = new TextEncoder().encode(str);
    let binary = '';
    for (const b of bytes) binary += String.fromCharCode(b);
    return btoa(binary);
}
